# Generated by Django 3.1 on 2021-09-04 23:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210902_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='No imagee', upload_to=products.models.upload_image_path),
            preserve_default=False,
        ),
    ]
